name: Task 1 - CI Pipeline with Tests

on:
  push:
    branches:
      - main
    paths:
      - 'tasks/1 задание/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r "tasks/1 задание/requirements.txt"
      
      - name: Run unit tests
        run: |
          cd "tasks/1 задание"
          pytest unit_test.py
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tasks/1 задание
          file: ./tasks/1 задание/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task1:latest
          provenance: false
