name: Task 4 - Auto Build Docker Image

on:
  push:
    paths:
      - 'tasks/4 задание/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tasks/4 задание
          file: ./tasks/4 задание/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task4:latest
          provenance: false
